pygments:       true
permalink:      /:categories/:title/
paginate:       5

exclude:
    - README.md

title:          AppDen
url:            http://appden.com
feed:           /atom.xml
description:    "Advanced JavaScript techniques, tips on avoiding those nasty CSS bugs, and musings on technological progress."
comment:        Jekyll is awesome

author:
    name:       Scott Kyle
    email:      scott@appden.com
    twitter:    appden
    
about: >
    Hi, I'm Scott Kyle, a JavaScript and Apple enthusiast.
    I recently became an offical developer for <a href="http://mootools.net">MooTools</a>.
    You can follow me on <a href="http://twitter.com/appden">Twitter</a>, fork me
    <a href="http://github.com/appden">GitHub</a>, and check out some of my recent work
    on my <a href="/portfolio/">portfolio</a>.
    
disqus:
    id:         appden

nav:
    - name:     Blog
      url:      /
      
    - name:     Apps
      subnav:
        - name: Coming Soon
    
    - name:     Projects
      subnav:
        - name: Coming Soon
        
    - name:     About
      url:      /about/
      subnav:
        - name: Portfolio
          url:  /portfolio/
          
        - name: Contact
          url:  mailto:scott-at-dotcom-after-appden
    

footer:
    - verb:     Thinking
      action:   "YAML &gt; JSON"

    - verb:     Listening
      action:   Pandora of course
      
copyright:
    - Design by <a href="http://ipsleung.com">Iris Leung</a>
    - "&copy; Copyright 2009, AppDen. All Rights Reserved."
      
css:
    - /lib/appden.css
    - /lib/syntax.css
    
js:
    - http://ajax.googleapis.com/ajax/libs/mootools/1.2.4/mootools-yui-compressed.js
    - /lib/mootools-more.js
    - /lib/appden.js
