pygments:       true
permalink:      /:categories/:title/
paginate:       13
markdown:       rdiscount

exclude:
    - README.md
      Rakefile

title:          Haeg.in
url:            http://haeg.in
feed:           /atom.xml
description:    "What I make of it"
comment:        As this is a comment it is unreadable to the general populance

author:
    name:       Harry Mills
    email:      harry-at-dotin-after-haeg
    twitter:    Haegin

disqus:
    id:         haegin

nav:
    - name:     Home
      url:      /
    - name:     Blog
      url:      /blog.html
#    - name:     Gallery
#      url:      /gallery/
#    - name:     Archive
#      url:      /archive.html
    - name:     About
      url:      /about.html

footer:
    - verb:     Watching
      action:   "Too much TV. Currently I'm following Chuck, Castle and The Big Bang Theory and catching up on House and How I Met Your Mother."

    - verb:     Developing
      action:   Website for the <a href='http://umoyoorphanproject.org'>Umoyo Orphan Project</a>.

    - verb:     Reading
      action:   Greyhawk Adventures by Gary Gygax.

copyright:
    - Design by <a href="http://haeg.in">Harry Mills</a>
    - "&copy; Copyright 2010, Haeg.in. All Rights Reserved."

css:
    - /css/combined.css.min
#    - /css/reset.css.min
#    - /css/layout.css.min
#    - /css/style.css.min
#    - /css/syntax.css.min

js:
    - /lib/combined.js.min
    - http://www.google.com/jsapi?key=ABQIAAAA_kruhSKAcNICee45fs0guhRlSyQPnyLBQs_-b4rjto02oZxXzBTXtWdJySHVtWsktpAArWDCN8wqhw
#    - /lib/analytics.js.min
