pygments:       true
permalink:      /:categories/:title/
paginate:       13
markdown:       rdiscount

exclude:
    - README.md
      Rakefile

title:          Haeg.in
url:            http://haeg.in
feed:           /atom.xml
description:    "What I make of it"
comment:        As this is a comment it is unreadable to the general populance

author:
    name:       Harry Mills
    email:      harry-at-dotin-after-haeg
    twitter:    Haegin

about: >
    Haegin has yet to write an about section for his site but when he does it may or may
    not be in the third person.

disqus:
    id:         haegin

nav:
    - name:     Blog
      url:      /

#    - name:     Gallery
#      url:      /gallery/

    - name:     About
      url:      /about/

footer:
    - verb:     Watching
      action:   "Too much TV. Currently I'm following Chuck, Castle and The Big Bang Theory and catching up on House and How I Met Your Mother."

    - verb:     Developing
      action:   Website for the <a href='http://umoyoorphanproject.org'>Umoyo Orphan Project</a>.

    - verb:     Reading
      action:   Gormenghast by Mervyn Peake.

copyright:
    - Design by <a href="http://ipsleung.com">Iris Leung</a>
    - "&copy; Copyright 2009, AppDen. All Rights Reserved."

css:
    - /css/reset.css
    - /css/layout.css
    - /css/style.css
    - /css/syntax.css

js:
    - http://ajax.googleapis.com/ajax/libs/mootools/1.2.4/mootools-yui-compressed.js
    - /lib/mootools-more.js
    - /lib/site.js
